CREATE DATABASE IF NOT EXISTS voice_social DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'voice'@'%' IDENTIFIED BY 'voice123';
GRANT ALL PRIVILEGES ON voice_social.* TO 'voice'@'%';
FLUSH PRIVILEGES;
